# Generated by Django 4.0.4 on 2022-05-18 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnopedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 11, 15, 7, 920438)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 11, 15, 7, 921438)),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='isAdministrator',
            field=models.IntegerField(db_column='isAdministrator', default=False),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='isModerator',
            field=models.IntegerField(db_column='isModerator', default=False),
        ),
    ]
